runtime: php83
service: appdriver

handlers:
- url: /.*
  script: index.php
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/c-03-414902/appdriver', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/c-03-414902/appdriver']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'app', 'deploy', '--image-url=gcr.io/c-03-414902/appdriver']
